services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  celery:
    image: python:3.10
    container_name: celery
    command: bash -c "pip install -r requirements.txt && celery -A popcorngeek worker --loglevel=info"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"