# Generated by Django 5.1.1 on 2024-10-08 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_deactivate_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admonition",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="deactivate_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 10, 9, 0, 11, 4, 234286),
                null=True,
            ),
        ),
    ]
