# Generated by Django 4.2 on 2024-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남자"), ("F", "여자")],
                max_length=1,
                null=True,
            ),
        ),
    ]
