# Generated by Django 5.1.1 on 2024-10-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_deactivate_time"),
        ("accounts", "0007_user_is_suspended_user_suspended_time_and_more"),
    ]

    operations = []
