# Generated by Django 5.1.1 on 2024-10-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20241009_0328"),
        ("accounts", "0009_alter_user_deactivate_time"),
    ]

    operations = []
