# Generated by Django 5.1.1 on 2024-10-10 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_merge_20241010_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deactivate_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 10, 10, 21, 21, 33, 425120),
                null=True,
            ),
        ),
    ]
