# Generated by Django 5.1.1 on 2024-10-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_deactivate_time"),
        ("accounts", "0011_alter_user_deactivate_time"),
    ]

    operations = []
