# Generated by Django 4.2 on 2024-10-01 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0007_remove_like_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to="reviews.comment",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_likes",
                to="reviews.review",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
