# Generated by Django 5.1.1 on 2024-10-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_spoiler",
            field=models.BooleanField(default=False),
        ),
    ]
