# Generated by Django 5.1.1 on 2024-10-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_review_is_spoiler"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_spoiler",
            field=models.BooleanField(default=False),
        ),
    ]
