# Generated by Django 5.1.1 on 2024-10-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_comment_is_spoiler"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_positive",
            field=models.BooleanField(null=True),
        ),
    ]
