# Generated by Django 5.1.1 on 2024-10-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0012_review_is_positive"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.CharField(default="inappropriate", max_length=13),
        ),
    ]
