# Generated by Django 5.1.1 on 2024-10-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0013_report_report_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="followers_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
