# Generated by Django 4.2 on 2024-09-27 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("rank", models.PositiveIntegerField()),
                ("crawling_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_cd", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=50)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("plot", models.TextField(blank=True)),
                (
                    "like_users",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.tag"
                    ),
                ),
            ],
        ),
    ]
