# Generated by Django 4.2 on 2024-09-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_cd", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=50)),
                ("runtime", models.IntegerField(blank=True)),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("plot", models.TextField(blank=True)),
            ],
        ),
    ]
