# Generated by Django 4.2 on 2024-09-26 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0002_tag_movie_like_users_movie_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="like_users",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
