# Generated by Django 4.2 on 2024-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_runtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="grade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
