# Generated by Django 4.2 on 2024-09-27 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0005_alter_movie_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="dislike_users",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_movies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="like_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_movies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
