# Generated by Django 5.1.1 on 2024-10-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_alter_ranking_movie_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="prodYear",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
