# Generated by Django 5.1.1 on 2024-10-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movie_prodyear"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="prodYear",
            new_name="prodyear",
        ),
    ]
