# Generated by Django 5.1.1 on 2024-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_rename_prodyear_movie_prodyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="movie_pk",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
