# Generated by Django 5.1.1 on 2024-10-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_alter_ranking_movie_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
