# Generated by Django 5.1.1 on 2024-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="movie_pk",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
