# Generated by Django 5.1.1 on 2024-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_alter_ranking_movie_pk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="prodyear",
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
