# Generated by Django 5.1.1 on 2024-10-08 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_remove_movie_prodyear_movie_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="movie_pk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking",
                to="movies.movie",
            ),
        ),
    ]
