name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.14]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        POSTGRES_DB: ${{ secrets.DB_NAME }}
        POSTGRES_USER: ${{ secrets.DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.DB_HOST }}
        POSTGRES_PORT: 5432
        KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
        KMDB_API_KEY: ${{ secrets.KMDB_API_KEY }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        IMP_KEY: ${{ secrets.IMP_KEY }}
        IMP_SECRET: ${{ secrets.IMP_SECRET }}
        KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
        NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        DJANGO_DEBUG: "false"
      run: |
        python manage.py test

