# Generated by Django 5.1.1 on 2024-10-12 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_purchasedproduct_rename_title_product_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedproduct",
            name="address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasedproduct",
            name="address2",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasedproduct",
            name="amount",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasedproduct",
            name="merchant_uid",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasedproduct",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased",
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchasedproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "결제완료"),
                    ("B", "배송대기"),
                    ("C", "배송중"),
                    ("D", "배송완료"),
                ],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="purchasedproduct",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
