# Generated by Django 5.1.1 on 2024-10-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_purchasedproduct_address_purchasedproduct_address2_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasedproduct",
            old_name="amount",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="purchasedproduct",
            name="merchant_uid",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
