# Generated by Django 5.1.1 on 2024-10-17 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_amount_purchasedproduct_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="consumer",
            field=models.ManyToManyField(
                related_name="basket", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
