# Generated by Django 5.1.1 on 2024-10-18 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_consumer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="consumer",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="basket",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
