# Generated by Django 5.1.1 on 2024-10-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_purchasedproduct_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedproduct",
            name="merchant_uid",
            field=models.CharField(max_length=50),
        ),
    ]
